CREATE TABLE public.user(
	id_user BIGSERIAL NOT NULL CONSTRAINT public_user_pkey PRIMARY KEY,
	id_gallery BIGINT NOT NULL CONSTRAINT public_user_gallery_fkey REFERENCES public.gallery(id_gallery) MATCH SIMPLE ON UPDATE CASCADE ON DELETE RESTRICT,
	first_name CHARACTER VARYING(20) NOT NULL,
	last_name CHARACTER VARYING(20) NOT NULL,
	email CHARACTER VARYING(60) NOT NULL,
	pass CHARACTER VARYING(32) NOT NULL,
	is_admin BOOLEAN NOT NULL DEFAULT FALSE
) with(
oids=false
);
